# the keyboard devices it reads from, if no devices are specified, it reads from all
devices:
# - "/dev/input/by-id/SOME_KEYBOARD_REPLACE_ME-event-kbd"

# this is executed when mouseless starts, e.g. useful for setting the keyboard layout
# startCommand: "setxkbmap de"

# the default speed for mouse movement and scrolling
baseMouseSpeed: 750.0
baseScrollSpeed: 15.0

# the time it takes to accelerate to baseMouseSpeed (in ms), 0 to reach top speed immediately
mouseAccelerationTime: 0
# the shape of the acceleration curve, 1.0 is linear, higher values have more time at low speeds
mouseAccelerationCurve: 1.0 # speed of the mouse when it starts moving startMouseSpeed: 0.0 # same for deceleration mouseDecelerationTime: 0
mouseDecelerationCurve: 1.0

# the rest of the config defines the layers with their bindings
layers:
# the first layer is active at start
- name: initial
  bindings:
    # when tab is held and another key pressed, activate mouse layer
    capslock: toggle-layer mouse

# a layer for mouse movement
- name: mouse
  # when true, keys that are not mapped keep their original meaning
  passThrough: true 
  bindings:
    # quit mouse layer
    q: layer initial
    esc: layer initial
    # keep the mouse layer active
    space: layer mouse
    r: reload-config
    l: move  1  0
    h: move -1  0
    j: move  0  1
    k: move  0 -1
    p: scroll up
    n: scroll down
    leftalt: speed 4.0
    leftmeta: speed 6.0
    a: speed 0.3
    s: button left
    d: button middle
    f: button right
    enter: capslock
    # move to the top left corner
    k0: "exec xdotool mousemove 0 0"
